import os
import re
import ast
import sys
import json
sys.path.insert(0, "../..")

import argparse
import nltk
import torch
import pandas as pd
from nltk.stem import PorterStemmer
from src.Interpretable_RAG.rag import ExplainableAutoModelForRAG
from src.experiments.perturbations import PromptPerturbationModule

nltk.download('punkt_tab', quiet=True)


def _ret_token_processor(s: str) -> str:
    return s.replace('▁', ' ')

def _gen_token_processor(s: str) -> str:
    return s.replace('Ġ', ' ').strip('Ċ')


_stemmer = PorterStemmer()

def _normalize_text(text: str) -> list[str]:
    return [_stemmer.stem(w) for w in re.findall(r'[^\s\.,;:!?\(\)\[\]{}_\-\+\*]+', text.lower())]

def _supports(prediction: str, ground_truths: list[str]) -> float:
    pred_tokens = _normalize_text(prediction)
    for gt in ground_truths:
        gt_tokens = _normalize_text(gt)

        n = len(gt_tokens)
        if n == 0: continue

        for i in range(0, len(pred_tokens)-n+1):
            if pred_tokens[i:i+n] == gt_tokens:
                return True
    return False


#================================================================================#
# Initialization arguments for supported modules:                                #
#================================================================================#
RET_INIT_ARGS = {
    'dragon': {
        'query_encoder_name_or_path': 'facebook/dragon-plus-query-encoder',
        'context_encoder_name_or_path': 'facebook/dragon-plus-context-encoder',
        'retriever_token_processor': _ret_token_processor,
    },
    'snowflake': {
        'query_encoder_name_or_path': 'Snowflake/snowflake-arctic-embed-l-v2.0',
        'retriever_query_format': 'query: {query}',
        'retriever_token_processor': _ret_token_processor,
        'retriever_kwargs': {'add_pooling_layer': False},
    },
}

GEN_INIT_ARGS = {
    'llama8B': {
        'generator_name_or_path': 'meta-llama/Llama-3.1-8B-Instruct',
        'generator_token_processor': _gen_token_processor,
        'generator_kwargs': {'device_map': 'auto', 'dtype': torch.bfloat16},
    },
    'qwen7B': {
        'generator_name_or_path': 'Qwen/Qwen2.5-7B-Instruct',
        'generator_token_processor': _gen_token_processor,  # BPE tokenizer, same Ġ prefix
        'generator_kwargs': {'device_map': 'auto', 'dtype': torch.bfloat16},
    },
    'gemma3_12B': {
        'generator_name_or_path': 'google/gemma-3-12b-it',
        'generator_token_processor': _ret_token_processor,  # SentencePiece tokenizer, ▁ prefix
        'generator_kwargs': {'device_map': 'auto', 'dtype': torch.bfloat16},
    },
}

#================================================================================#
# Call-time arguments for supported modules:                                     #
#================================================================================#
RET_CALL_ARGS = {
    'dragon': {'retriever_kwargs': {'max_length': 512}},
    'snowflake': {'retriever_kwargs': {}},
}

GEN_CALL_ARGS = {
    'llama8B': {
        'generator_kwargs': {
            'max_new_tokens': 256,
            'do_sample': False,
            'top_p': 1,
            'num_beams': 1,
            'batch_size': 32,
            'max_samples_query': 32,
            'max_samples_context': 32,
            'conditional': True,
        },
    },
    'qwen7B': {
        'generator_kwargs': {
            'max_new_tokens': 256,
            'do_sample': False,
            'top_p': 1,
            'num_beams': 1,
            'batch_size': 32,
            'max_samples_query': 32,
            'max_samples_context': 32,
            'conditional': True,
        },
    },
    'gemma3_12B': {
        'generator_kwargs': {
            'max_new_tokens': 256,
            'do_sample': False,
            'top_p': 1,
            'num_beams': 1,
            'batch_size': 16,
            'max_samples_query': 32,
            'max_samples_context': 32,
            'conditional': True,
        },
    },
}

#================================================================================#
# Folder names for supported modules:                                            #
#================================================================================#
RET_FOLDERS = {
    'dragon': 'facebook-dragon-plus',
    'snowflake': 'snowflake-arctic-embed-l-v2.0',
}

GEN_FOLDERS = {
    'llama8B': 'llama-3.1-8b-instruct',
    'qwen7B': 'qwen2.5-7b-instruct',
    'gemma3_12B': 'gemma-3-12b-it',
}

# Perturbation conditions generated by PromptPerturbationModule:
#   Setup A (Top-k vs Low-k):          A1=[top,low],    A2=[low,top],    A3=shuffled
#   Setup B (Top-k vs Random-corpus):  B1=[top,random], B2=[random,top], B3=shuffled
#   Setup C (Top-k vs Adjacent-k):     C1=[top,adj],    C2=[adj,top],    C3=shuffled
CONDITION_KEYS = ['B1', 'B2', 'B3']

#================================================================================#
# Main function:                                                                 #
#================================================================================#
def main(generator: str, retriever: str, k: int = 5, devices: str | None = None):
    results_dir = f'../../results/{RET_FOLDERS[retriever]}/{GEN_FOLDERS[generator]}'
    warg_path = f'{results_dir}/warg_popqa.csv'
    corpus_path = f'../../data/popqa/{RET_FOLDERS[retriever]}/documents.json'
    perturb_path = f'{results_dir}/perturbations_popqa.csv'
    perturbations_dir = f'{results_dir}/perturbations_popqa/'

    os.makedirs(perturbations_dir, exist_ok=True)

    if devices is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = devices

    with open(corpus_path) as f:
        corpus = json.load(f)

    model = ExplainableAutoModelForRAG(**RET_INIT_ARGS[retriever], **GEN_INIT_ARGS[generator])
    perturbations = PromptPerturbationModule(seed=42)

    warg = pd.read_csv(warg_path, index_col=None)

    gen_cols = {c: f'generation_{c}' for c in CONDITION_KEYS}
    if os.path.exists(perturb_path):
        results = pd.read_csv(perturb_path, index_col=None)
    else:
        results = warg[['query_id', 'query', 'possible_answers', 'passages']].copy()
        for col in gen_cols.values():
            results[col] = None

    for i, (qry, ctx_raw) in enumerate(results[['query', 'passages']].values):
        ranked_docs = eval(ctx_raw)

        conditions = {}
        if any(k.startswith('A') for k in CONDITION_KEYS):
            conditions.update(perturbations.generate_setup_a(ranked_docs, k=k))
        if any(k.startswith('B') for k in CONDITION_KEYS):
            conditions.update(perturbations.generate_setup_b(ranked_docs[:k], corpus, k=k))
        if any(k.startswith('C') for k in CONDITION_KEYS):
            conditions.update(perturbations.generate_intertwined_setup(ranked_docs, k=k))

        ret_kwargs = RET_CALL_ARGS[retriever].get('retriever_kwargs', {})
        gen_kwargs = GEN_CALL_ARGS[generator]['generator_kwargs']

        for cond_key in CONDITION_KEYS:
            cond_docs = conditions[cond_key]
            col = gen_cols[cond_key]
            if not pd.isnull(results.loc[i, col]):
                print(f'Skipping query {i:d} condition {cond_key}.')
                continue

            # Encode contexts with the retriever keeping cond_docs order in the
            # internal state (reorder=False).  The returned document list is
            # discarded; what matters is that self._x['context'] is ordered to
            # match the order we pass to the generator below.
            model.retriever(
                model.retriever_query_format.format(query=qry),
                contexts=cond_docs,
                k=len(cond_docs),
                reorder=False,
                output_texts=False,
                compute_grad=False,
                output_attentions=False,
                output_hidden_states=False,
                **ret_kwargs,
            )

            # Generate with cond_docs in their exact perturbed order.
            results.loc[i, col] = model.generator.explain_generate(
                qry, cond_docs, **gen_kwargs,
            )[-1]['content']

            model.save_values(
                perturbations_dir, f'{cond_key.lower()}_{i:d}.pkl',
                ret_methods=['intGrad'], gen_aggregations=['token'], batch_size=16,
            )
        

        results.to_csv(perturb_path, index=False)

    for cond_key, col in gen_cols.items():
        supp_col = f'supp_{cond_key}'
        results[supp_col] = results.apply(
            lambda row: _supports(
                str(row[f'generation_{cond_key}']),
                ast.literal_eval(row['possible_answers']),
            ) if pd.notna(row[f'generation_{cond_key}']) else float('nan'),
            axis=1,
        )
    results.to_csv(perturb_path, index=False)

#================================================================================#
# Command line interface:                                                        #
#================================================================================#
if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Run perturbation experiments on the PopQA dataset.'
    )
    parser.add_argument(
        '--generator',
        choices=list(GEN_INIT_ARGS.keys()),
        required=True,
        help='Generator model to use.',
    )
    parser.add_argument(
        '--retriever',
        choices=list(RET_INIT_ARGS.keys()),
        required=True,
        help='Retriever model to use.',
    )
    parser.add_argument(
        '--k',
        type=int,
        default=5,
        help='Number of top/low/random documents per perturbation condition (default: 10).',
    )
    parser.add_argument(
        '--devices',
        default=None,
        help='Comma-separated CUDA device indices (e.g. "0,1"). Defaults to all visible devices.',
    )
    args = parser.parse_args()
    main(generator=args.generator, retriever=args.retriever, k=args.k, devices=args.devices)