import pickle
import numpy as np
import torch
import argparse
import os

def explain_pickle(filepath):
    print(f"--- Explanation for {os.path.basename(filepath)} ---")
    with open(filepath, 'rb') as f:
        data = pickle.load(f)
    
    print("This pickle file contains results from the RAG pipeline.")
    
    if 'gen_tokens' in data:
        print("\nType: GENERATION Results")
        print("This file contains the generated response and the attribution scores (Shapley values) indicating feature importance.")
        
        print("\nKey Contents:")
        print("- 'model_name_or_path': The LLM used for generation.")
        print(f"- 'qry_tokens': The tokens of the input query. (Count: {len(data.get('qry_tokens', []))})")
        print(f"- 'gen_tokens': The tokens generated by the model. (Count: {len(data.get('gen_tokens', []))})")
        
        print("\nAttribution Scores (Shapley Values):")
        print("These scores measure how much each input token contributed to the generation of each output token.")
        
        if 'shapley_values_token' in data:
            print("- 'shapley_values_token': Token-level importance.")
            sv = data['shapley_values_token']
            if 'query' in sv:
                shape = sv['query'].shape
                print(f"  - 'query': Shape {shape} -> (num_query_tokens, num_generated_tokens).")
                print("    Each cell [i, j] represents the contribution of query token i to generated token j.")
            if 'context' in sv:
                shape = sv['context'].shape
                print(f"  - 'context': Shape {shape} -> (num_context_chunks, num_generated_tokens).")
                
    elif 'input' in data and 'intGrad' in data:
        print("\nType: RETRIEVAL Results")
        print("This file contains the retrieval query/context and gradient-based importance scores.")
        
        print("\nKey Contents:")
        print("- 'input': The tokenized query and context.")
        if 'query' in data['input']:
             print(f"  - Query tokens: {data['input']['query'][0]}")
        
        print("\nImportance Scores:")
        print("These scores measure the importance of input tokens for the retrieval ranking/score.")
        
        score_descs = {
            'grad': 'Raw Gradients',
            'intGrad': 'Integrated Gradients (more robust attribution)',
            'gradIn': 'Gradient * Input',
            'aGrad': 'Alignment Gradient'
        }
        
        for key, desc in score_descs.items():
            if key in data:
                print(f"- '{key}': {desc}")
                if 'query' in data[key]:
                    val = data[key]['query']
                    if isinstance(val, torch.Tensor):
                        print(f"  - Shape: {val.shape}")
    
    else:
        print("\nType: Unknown structure")
        print(f"Keys found: {list(data.keys())}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("filepath", help="Path to pickle file")
    args = parser.parse_args()
    explain_pickle(args.filepath)
